BOOT_LOGO=wvga
MTK_PLATFORM=MT6577
MTK_NAND_PAGE_SIZE=4K
GEMINI=yes
MTK_GEMINI_ENHANCEMENT=no
MTK_SHARE_MODEM_CURRENT=2
MTK_SHARE_MODEM_SUPPORT=2
MTK_RAT_WCDMA_PREFERRED=no
MTK_BSP_PACKAGE=yes
CUSTOM_HAL_IMGSENSOR=hi542_mipi_raw
CUSTOM_HAL_MAIN_IMGSENSOR=hi542_mipi_raw
CUSTOM_HAL_MSENSORLIB=mmc328x akm8975  ami304 yamaha530 mag3110 akmd8963
CUSTOM_HAL_SUB_IMGSENSOR=
CUSTOM_KERNEL_ACCELEROMETER=bma222
CUSTOM_KERNEL_ALSPS=tmd2771
CUSTOM_KERNEL_IMGSENSOR=hi542_mipi_raw
CUSTOM_KERNEL_LCM=lg4573ba_wvga_lh430mv1_dsi_vdo
CUSTOM_KERNEL_MAIN_IMGSENSOR=hi542_mipi_raw
CUSTOM_KERNEL_SOUND=amp_tpa2055d3
CUSTOM_KERNEL_SUB_IMGSENSOR=
CUSTOM_KERNEL_TOUCHPANEL=synaptics_3000
CUSTOM_KERNEL_USB=mt6575
CUSTOM_KERNEL_CHARGEPUMP=lm3530
CUSTOM_MODEM=lge77hdk_e1_evb_hspa
CUSTOM_UBOOT_LCM=lg4573ba_wvga_lh430mv1_dsi_vdo
CUSTOM_LK_LCM=lg4573ba_wvga_lh430mv1_dsi_vdo

CUSTOM_HAL_LENS=fm50af
CUSTOM_HAL_MAIN_LENS=fm50af 
CUSTOM_KERNEL_LENS=fm50af
CUSTOM_KERNEL_MAIN_LENS=fm50af

CUSTOM_EXT_CHARGER_IC_SUPPORT=yes
CUSTOM_LK_EXT_CHARGER=miniabb
CUSTOM_KERNEL_EXT_CHARGER=miniabb

MTK_LCM_PHYSICAL_ROTATION=180

DEFAULT_LATIN_IME_LANGUAGES=en_US

MTK_75DISPLAY_ENHANCEMENT_SUPPORT=no

MTK_APKINSTALLER_APP=yes
MTK_ASF_PLAYBACK_SUPPORT=no

MTK_DM_APP=no

MTK_EAP_SIM_AKA=yes

MTK_FSCK_MSDOS_MTK=no

MTK_GOOGLEOTA_SUPPORT=no

MTK_LAUNCHER_UNREAD_SUPPORT=no

MTK_MASS_STORAGE=no

MTK_SENSOR_SUPPORT=yes
MTK_SPECIFIC_SM_CAUSE=yes

MTK_SMSREG_APP=no

MTK_TTY_SUPPORT=yes

RESOURCE_OVERLAY_SUPPORT=
MTK_AUDIO_GAIN_TABLE_SUPPORT = yes
OPTR_SPEC_SEG_DEF=NONE

MTK_RELEASE_PACKAGE=rel_customer_basic

CUSTOM_KERNEL_BATTERY = battery

MTK_CALENDAR_IMPORTER_APP=no
MTK_FILEMANAGER_APP=no
MTK_MAV_SUPPORT=no
MTK_VIDEOPLAYER_APP=no
MTK_VLW_APP=no
MTK_VT3G324M_SUPPORT=no
MTK_WEATHER_PROVIDER_APP=no
MTK_WEATHER_WIDGET_APP=no
MTK_WORLD_CLOCK_WIDGET_APP=no
MTK_SOUNDRECORDER_APP=yes
MTK_WVDRM_SUPPORT=no
MTK_DRM_APP=no
MTK_THEMEMANAGER_APP=no
MTK_WEATHER3D_WIDGET=no

MTK_BT_21_SUPPORT = yes
MTK_BT_30_HS_SUPPORT = no
MTK_BT_30_SUPPORT = yes
MTK_BT_40_LE_STANDALONE = no
MTK_BT_40_SUPPORT = no
MTK_BT_FM_OVER_BT_VIA_CONTROLLER = no
MTK_BT_POWER_EFFICIENCY_ENHANCEMENT = no
MTK_BT_PROFILE_A2DP = yes
MTK_BT_PROFILE_AVRCP = yes
MTK_BT_PROFILE_AVRCP13 = yes
MTK_BT_PROFILE_AVRCP14 = no
MTK_BT_PROFILE_BIP = no
MTK_BT_PROFILE_BPP = no
MTK_BT_PROFILE_DUN = no
MTK_BT_PROFILE_FTP = yes
MTK_BT_PROFILE_HFP = yes
MTK_BT_PROFILE_HIDH= yes
MTK_BT_PROFILE_MANAGER = yes
MTK_BT_PROFILE_MAPC = no
MTK_BT_PROFILE_MAPS = yes
MTK_BT_PROFILE_OPP = yes
MTK_BT_PROFILE_PAN = yes
MTK_BT_PROFILE_PBAP = yes
MTK_BT_PROFILE_PRXM = no
MTK_BT_PROFILE_PRXR = no
MTK_BT_PROFILE_SIMAP = no
MTK_BT_PROFILE_SPP = yes
MTK_BT_PROFILE_TIMEC = no
MTK_BT_PROFILE_TIMES = no
MTK_BICR_SUPPORT=no


HAVE_SRSAUDIOEFFECT_FEATURE=no

MTK_NFC_SUPPORT = yes
MTK_NFC_INSIDE = yes 
ENCRY_PARTITION_SUPPORT=yes
MTK_MULTI_PATCH_SUPPORT=yes
